### ISSUE TITLE
What is the meaning of different alias tables?

### ISSUE THREAD

**Issue by liumx10** [nvmwrap/softwrap#1]
I am reading your MAST paper and find the design of alias table is interesting. However, I am confused by different alias tables in this project. Can you help explaining this thing in README ?

According to my understanding, LAT means "local alias table ?"  If so, it seems LAT does not provide atomically **restoreToCacheHierarchy** . 
For example, if thread A write x, write y;  and thread B read x, read y just between two writes of thread A.
Inconsistency happens here.

**Comment by ellisgiles** [comment]
SoftWrAP in the version you reference assumes concurrency control is correctly handled by the programmer, e.g. it is not a heavyweight STM, but is easily extendible to be so.
